/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;
import DAO.Item;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Login.UserLogin;
import javax.swing.JOptionPane;
/**
 *
 * @author ayush
 */
public class AddItems extends javax.swing.JFrame {

    /**
     * Creates new form AddItems
     */
    Item item;
    public AddItems() {
        item = new Item();
        initComponents();
    }
    String curr = "";
    int number = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        quantityfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD ITEMS");
        setResizable(false);
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dress", "Books", "Shoes", "Stationery", "Bag" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(357, 102, 272, 50);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Item");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 100, 120, 50);

        quantityfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityfieldActionPerformed(evt);
            }
        });
        getContentPane().add(quantityfield);
        quantityfield.setBounds(357, 204, 136, 41);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantity");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 210, 100, 22);

        jButton1.setBackground(new java.awt.Color(255, 212, 49));
        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 350, 96, 41);

        jButton2.setBackground(new java.awt.Color(255, 212, 49));
        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(640, 500, 72, 34);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Image16.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 800, 655);

        setSize(new java.awt.Dimension(810, 661));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed
    
    // store the quntity in the variable curr
    private void quantityfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityfieldActionPerformed
        curr = quantityfield.getText();
    }//GEN-LAST:event_quantityfieldActionPerformed
    
    // when the save button is clicked
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if("Enter Quantity".equals(quantityfield.getText()) || "".equals(quantityfield.getText()))
            JOptionPane.showMessageDialog(null,"Quantity cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(!quantityfield.getText().trim().matches("[0-9]+"))
            JOptionPane.showMessageDialog(null,"Invalid Quantity Entered" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else
        {
            int input;
            input = JOptionPane.showConfirmDialog(AddItems.this,"Do you really want to update this information?","Are you sure?",JOptionPane.YES_NO_OPTION);
            if( input == 0)
            {       
                    number = Integer.parseInt(curr);
                    int i = item.updateQuantity(jComboBox1.getSelectedItem().toString(), number);
                    if(i>0){
                            JOptionPane.showMessageDialog(null, "Information updated Successfully", "Success!", JOptionPane.INFORMATION_MESSAGE);	
                    }
                    else{
                            JOptionPane.showMessageDialog(AddItems.this,"Sorry, unable to save!");
                    }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // when the back button is clicked
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        UserDashboard.main(new String[]{});
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField quantityfield;
    // End of variables declaration//GEN-END:variables
}
