/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;
import DAO.Student;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.*;
import java.util.Arrays;
/**
 *
 * @author ayush
 */
public class AddStudent extends javax.swing.JFrame {

    /**
     * Creates new form AddStudent
     */
    Student user;
    public AddStudent() {
        user = new Student();
        initComponents();
    }
    
    String p_age;
    String p_class;
    String p_percent;
    String p_income;
    String p_amount;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namefield = new javax.swing.JTextField();
        agefield = new javax.swing.JTextField();
        classfield = new javax.swing.JTextField();
        schoolfield = new javax.swing.JTextField();
        percentfield = new javax.swing.JTextField();
        incomefield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        amountfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dresscheck = new javax.swing.JCheckBox();
        bookscheck = new javax.swing.JCheckBox();
        shoescheck = new javax.swing.JCheckBox();
        stationerycheck = new javax.swing.JCheckBox();
        bagcheck = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        savebutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        genderbox = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADD STUDENT");
        setResizable(false);
        getContentPane().setLayout(null);

        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        getContentPane().add(namefield);
        namefield.setBounds(194, 94, 230, 37);

        agefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agefieldActionPerformed(evt);
            }
        });
        getContentPane().add(agefield);
        agefield.setBounds(194, 175, 90, 33);

        classfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classfieldActionPerformed(evt);
            }
        });
        getContentPane().add(classfield);
        classfield.setBounds(194, 283, 76, 34);

        schoolfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                schoolfieldActionPerformed(evt);
            }
        });
        getContentPane().add(schoolfield);
        schoolfield.setBounds(194, 435, 240, 34);

        percentfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentfieldActionPerformed(evt);
            }
        });
        getContentPane().add(percentfield);
        percentfield.setBounds(194, 515, 240, 36);

        incomefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incomefieldActionPerformed(evt);
            }
        });
        getContentPane().add(incomefield);
        incomefield.setBounds(194, 592, 240, 33);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setText("Enter name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 100, 90, 17);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("Enter Age");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(105, 183, 80, 17);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel3.setText("Enter Class");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 290, 100, 17);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel4.setText("Enter Gender");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 360, 110, 17);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel5.setText("Enter School");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(81, 444, 110, 17);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel6.setText("Enter percent");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(65, 525, 110, 17);

        jLabel7.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel7.setText("Enter income");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(65, 600, 110, 17);

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Forms of Help required");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(590, 110, 370, 37);

        amountfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountfieldActionPerformed(evt);
            }
        });
        getContentPane().add(amountfield);
        amountfield.setBounds(690, 180, 140, 38);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel9.setText("Enter amount");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(570, 180, 120, 17);

        dresscheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dresscheckActionPerformed(evt);
            }
        });
        getContentPane().add(dresscheck);
        dresscheck.setBounds(710, 270, 19, 19);

        bookscheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookscheckActionPerformed(evt);
            }
        });
        getContentPane().add(bookscheck);
        bookscheck.setBounds(710, 310, 19, 19);

        shoescheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shoescheckActionPerformed(evt);
            }
        });
        getContentPane().add(shoescheck);
        shoescheck.setBounds(710, 350, 19, 19);

        stationerycheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stationerycheckActionPerformed(evt);
            }
        });
        getContentPane().add(stationerycheck);
        stationerycheck.setBounds(710, 390, 19, 19);

        bagcheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagcheckActionPerformed(evt);
            }
        });
        getContentPane().add(bagcheck);
        bagcheck.setBounds(710, 430, 19, 19);

        jLabel10.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel10.setText("Dress");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(630, 270, 50, 22);

        jLabel11.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel11.setText("Books");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(630, 310, 50, 20);

        jLabel12.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel12.setText("Shoes");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(630, 350, 60, 17);

        jLabel13.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel13.setText("Stationery");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(600, 390, 100, 17);

        jLabel14.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel14.setText("Bag");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(650, 430, 30, 17);

        savebutton.setBackground(new java.awt.Color(204, 255, 255));
        savebutton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        savebutton.setText("SAVE");
        savebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(savebutton);
        savebutton.setBounds(501, 592, 72, 33);

        backbutton.setBackground(new java.awt.Color(204, 255, 255));
        backbutton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton);
        backbutton.setBounds(831, 638, 80, 30);

        genderbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        genderbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderboxActionPerformed(evt);
            }
        });
        getContentPane().add(genderbox);
        genderbox.setBounds(194, 361, 100, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Image24.jpg"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, -20, 1020, 760);

        setSize(new java.awt.Dimension(1025, 725));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // below are the functions storing the data when it is entered in the respective text fields or check boxes
    
    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
        user.setName(namefield.getText());
    }//GEN-LAST:event_namefieldActionPerformed

    private void agefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agefieldActionPerformed
        // TODO add your handling code here:
        p_age = agefield.getText();
    }//GEN-LAST:event_agefieldActionPerformed

    private void classfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classfieldActionPerformed
        // TODO add your handling code here:
        p_class = classfield.getText();
    }//GEN-LAST:event_classfieldActionPerformed

    private void schoolfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_schoolfieldActionPerformed
        // TODO add your handling code here:
        user.setSchool(schoolfield.getText());
    }//GEN-LAST:event_schoolfieldActionPerformed

    private void percentfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentfieldActionPerformed
        // TODO add your handling code here:
        p_percent = percentfield.getText();
    }//GEN-LAST:event_percentfieldActionPerformed

    private void incomefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incomefieldActionPerformed
        // TODO add your handling code here:
        p_income = incomefield.getText();
    }//GEN-LAST:event_incomefieldActionPerformed

    private void amountfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountfieldActionPerformed
        // TODO add your handling code here:
        p_amount = amountfield.getText();
    }//GEN-LAST:event_amountfieldActionPerformed

    private void dresscheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dresscheckActionPerformed
        // TODO add your handling code here:
        user.setDress(1);
    }//GEN-LAST:event_dresscheckActionPerformed

    private void bookscheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookscheckActionPerformed
        // TODO add your handling code here:
        user.setBooks(1);
    }//GEN-LAST:event_bookscheckActionPerformed

    private void shoescheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shoescheckActionPerformed
        // TODO add your handling code here:
        user.setShoes(1);
    }//GEN-LAST:event_shoescheckActionPerformed

    // when the stationery check box is selected
    private void stationerycheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stationerycheckActionPerformed
        // TODO add your handling code here:
        user.setStationery(1);
    }//GEN-LAST:event_stationerycheckActionPerformed

    // when the check box is selected
    private void bagcheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagcheckActionPerformed
        // TODO add your handling code here:
        user.setBag(1);
    }//GEN-LAST:event_bagcheckActionPerformed

    // when the back button is clicked
    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        AdminDashboard.main(new String[]{});
        dispose();
    }//GEN-LAST:event_backbuttonActionPerformed
    
    // when the save button is clicked
    private void savebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebuttonActionPerformed
        // TODO add your handling code here:
        if("".equals(namefield.getText()))
            JOptionPane.showMessageDialog(null,"Name cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if("".equals(agefield.getText()))
            JOptionPane.showMessageDialog(null,"Age cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(!agefield.getText().trim().matches("[0-9]+"))
            JOptionPane.showMessageDialog(null,"Invalid Age" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if("".equals(classfield.getText()))
            JOptionPane.showMessageDialog(null,"Class cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(!classfield.getText().trim().matches("[0-9]+"))
            JOptionPane.showMessageDialog(null,"Invalid Class" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if("".equals(schoolfield.getText()))
            JOptionPane.showMessageDialog(null,"School cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if("".equals(percentfield.getText()))
            JOptionPane.showMessageDialog(null,"Percentage cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(!percentfield.getText().trim().matches("[0-9]+"))
            JOptionPane.showMessageDialog(null,"Invalid Percent" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(!incomefield.getText().trim().matches("[0-9]+"))
            JOptionPane.showMessageDialog(null,"Invalid Income" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if("".equals(incomefield.getText()))
            JOptionPane.showMessageDialog(null,"Parental Income cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(!amountfield.getText().trim().matches("[0-9]+"))
            JOptionPane.showMessageDialog(null,"Invalid Amount" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(user.validateData(namefield.getText(), Integer.parseInt(p_age), Integer.parseInt(p_class), genderbox.getSelectedItem().toString(), user.getSchool(), Integer.parseInt(p_percent), Integer.parseInt(p_income)))
            JOptionPane.showMessageDialog(null, "Record Already Exists" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else{
            int input;
            input = JOptionPane.showConfirmDialog(AddStudent.this,"Do you really want to add this student ?","Are you sure?",JOptionPane.YES_NO_OPTION);
            if( input == 0)
            {       
                    user.setAge(Integer.parseInt(p_age));
                    user.setClass(Integer.parseInt(p_class));
                    user.setPercent(Integer.parseInt(p_percent));
                    user.setIncome(Integer.parseInt(p_income));
                    user.setMoney(Integer.parseInt(p_amount));
                    user.setGender(genderbox.getSelectedItem().toString());
                    int i = user.save();
                    if(i>0){
                            JOptionPane.showMessageDialog(null, "Record Added Successfully", "Success!", JOptionPane.INFORMATION_MESSAGE);
                            AdminDashboard.main(new String[]{});
                            dispose();
                    }
                    else{
                            JOptionPane.showMessageDialog(AddStudent.this,"Sorry, unable to save!");
                    }
            }
        }
    }//GEN-LAST:event_savebuttonActionPerformed

    private void genderboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderboxActionPerformed

    }//GEN-LAST:event_genderboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agefield;
    private javax.swing.JTextField amountfield;
    private javax.swing.JButton backbutton;
    private javax.swing.JCheckBox bagcheck;
    private javax.swing.JCheckBox bookscheck;
    private javax.swing.JTextField classfield;
    private javax.swing.JCheckBox dresscheck;
    private javax.swing.JComboBox<String> genderbox;
    private javax.swing.JTextField incomefield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField percentfield;
    private javax.swing.JButton savebutton;
    private javax.swing.JTextField schoolfield;
    private javax.swing.JCheckBox shoescheck;
    private javax.swing.JCheckBox stationerycheck;
    // End of variables declaration//GEN-END:variables
}
