/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;
import Login.AdminLogin;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import Login.UserLogin;
import java.awt.event.WindowEvent;
/**
 *
 * @author ayush
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        showdonorlistbutton = new javax.swing.JButton();
        showitemslistbutton = new javax.swing.JButton();
        updateitemslistbutton = new javax.swing.JButton();
        donationbutton = new javax.swing.JButton();
        Logoutbutton = new javax.swing.JButton();
        addstudentbutton = new javax.swing.JButton();
        deletestudentbutton = new javax.swing.JButton();
        showstudentslistbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN DASHBOARD");
        setResizable(false);
        getContentPane().setLayout(null);

        showdonorlistbutton.setBackground(new java.awt.Color(238, 235, 235));
        showdonorlistbutton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        showdonorlistbutton.setText("Show Donor List");
        showdonorlistbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showdonorlistbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(showdonorlistbutton);
        showdonorlistbutton.setBounds(530, 130, 169, 60);

        showitemslistbutton.setBackground(new java.awt.Color(238, 235, 235));
        showitemslistbutton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        showitemslistbutton.setText("Show Items List");
        showitemslistbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showitemslistbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(showitemslistbutton);
        showitemslistbutton.setBounds(530, 260, 169, 60);

        updateitemslistbutton.setBackground(new java.awt.Color(238, 235, 235));
        updateitemslistbutton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        updateitemslistbutton.setText("Update Items List");
        updateitemslistbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateitemslistbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(updateitemslistbutton);
        updateitemslistbutton.setBounds(80, 130, 190, 60);

        donationbutton.setBackground(new java.awt.Color(238, 235, 235));
        donationbutton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        donationbutton.setText("Implement Donation");
        donationbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donationbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(donationbutton);
        donationbutton.setBounds(310, 490, 190, 60);

        Logoutbutton.setBackground(new java.awt.Color(238, 235, 235));
        Logoutbutton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        Logoutbutton.setText("Log Out");
        Logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(Logoutbutton);
        Logoutbutton.setBounds(623, 600, 120, 40);

        addstudentbutton.setBackground(new java.awt.Color(238, 235, 235));
        addstudentbutton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        addstudentbutton.setText("Add Student");
        addstudentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudentbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(addstudentbutton);
        addstudentbutton.setBounds(80, 260, 190, 62);

        deletestudentbutton.setBackground(new java.awt.Color(238, 235, 235));
        deletestudentbutton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        deletestudentbutton.setText("Delete Student");
        deletestudentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletestudentbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(deletestudentbutton);
        deletestudentbutton.setBounds(80, 390, 190, 60);

        showstudentslistbutton.setBackground(new java.awt.Color(238, 235, 235));
        showstudentslistbutton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        showstudentslistbutton.setText("Show Students List");
        showstudentslistbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showstudentslistbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(showstudentslistbutton);
        showstudentslistbutton.setBounds(520, 390, 190, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/dashboard_final.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 742);

        setSize(new java.awt.Dimension(810, 748));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // when the show items button is clicked
    private void showitemslistbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showitemslistbuttonActionPerformed
        ShowItems.main(new String[]{});
        dispose();
    }//GEN-LAST:event_showitemslistbuttonActionPerformed
    
    // when the logout button is clicked
    private void LogoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutbuttonActionPerformed
        AdminLogin.main(new String[]{});
        dispose();
    }//GEN-LAST:event_LogoutbuttonActionPerformed

    // when the show donor button is clicked
    private void showdonorlistbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showdonorlistbuttonActionPerformed
        ShowDonor.main(new String[]{});
        dispose();
    }//GEN-LAST:event_showdonorlistbuttonActionPerformed

    // when the delete student button is clicked
    private void deletestudentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletestudentbuttonActionPerformed
        // TODO add your handling code here:
        DeleteStudent.main(new String[]{});
        dispose();
    }//GEN-LAST:event_deletestudentbuttonActionPerformed

    // when the add student button is clicked
    private void addstudentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudentbuttonActionPerformed
        AddStudent.main(new String[]{});
        dispose();
    }//GEN-LAST:event_addstudentbuttonActionPerformed

    // when the show students button is clicked
    private void showstudentslistbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showstudentslistbuttonActionPerformed
        // TODO add your handling code here:
        ShowStudents.main(new String[]{});
        dispose();
    }//GEN-LAST:event_showstudentslistbuttonActionPerformed

    //when the update items button is clicked
    private void updateitemslistbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateitemslistbuttonActionPerformed
        // TODO add your handling code here:
        UpdateItems.main(new String[]{});
        dispose();
    }//GEN-LAST:event_updateitemslistbuttonActionPerformed

    // when the donate button is clicked
    private void donationbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donationbuttonActionPerformed
        // TODO add your handling code here:
        Donation.main(new String[]{});
        dispose();
    }//GEN-LAST:event_donationbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logoutbutton;
    private javax.swing.JButton addstudentbutton;
    private javax.swing.JButton deletestudentbutton;
    private javax.swing.JButton donationbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton showdonorlistbutton;
    private javax.swing.JButton showitemslistbutton;
    private javax.swing.JButton showstudentslistbutton;
    private javax.swing.JButton updateitemslistbutton;
    // End of variables declaration//GEN-END:variables
}
