/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;
import Controller.DB;
import DAO.Student;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author ayush
 */
public class Donation extends javax.swing.JFrame {

    /**
     * Creates new form Donation
     */
    Student nst = new Student();
    public Donation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SortedTable = new javax.swing.JTable();
        donatebutton = new javax.swing.JButton();
        checkexpbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DonationTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DONATION");
        setResizable(false);
        getContentPane().setLayout(null);

        SortedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(SortedTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 30, 1240, 290);

        donatebutton.setBackground(new java.awt.Color(225, 223, 223));
        donatebutton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        donatebutton.setText("Donate");
        donatebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                donatebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(donatebutton);
        donatebutton.setBounds(55, 73, 100, 30);

        checkexpbutton.setBackground(new java.awt.Color(225, 223, 223));
        checkexpbutton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        checkexpbutton.setText("Check Expenditure");
        checkexpbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkexpbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(checkexpbutton);
        checkexpbutton.setBounds(10, 330, 180, 30);

        backbutton.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton);
        backbutton.setBounds(60, 620, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/donation.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 200, 720);

        DonationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(DonationTable);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(200, 362, 1230, 330);

        jLabel2.setBackground(new java.awt.Color(0, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 15)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SORTED STUDENT DETAILS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, -2, 1230, 30);

        jLabel3.setBackground(new java.awt.Color(0, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tibetan Machine Uni", 1, 15)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DONATION DETAILS");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 330, 1230, 30);

        setSize(new java.awt.Dimension(1439, 721));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // returns the original balance
    public int returnorb(int orb)
    {
        return orb;
    }
    
    // returns the new balance
    public int returnneb(int neb)
    {
        return neb;
    }
    
    // it displays the table carrying the details of students in a sorted manner
    public void fetch() throws SQLException{
        Connection con = DB.getConnection();
        PreparedStatement pst1;
        pst1 = con.prepareStatement("Select student_id as'ID', name as 'Name', age as 'Age', Class, Gender, School, percentage as 'Percentage', parental_income as 'Income', Money, Dress, Books, Shoes, Stationery, Bag  from student_sorted");
        ResultSet rs1 = pst1.executeQuery();
        SortedTable.setModel(DbUtils.resultSetToTableModel(rs1));
        
    }
    
    // it diplays the final donation details of the students after the donation is performed
    public void fetch1() throws SQLException{
         Connection con = DB.getConnection();
         PreparedStatement pst1;
         pst1 = con.prepareStatement("Select student_id as 'ID', name as 'Name', donated_Money as 'Money Donated', donated_Dress as 'Dress Donated', donated_Books as 'Books Donated', donated_Shoes as 'Shoes Donated', donated_Stationery as 'Stationery Donated', donated_Bag as 'Bag Donated' from student_sorted");
         ResultSet rs1 = pst1.executeQuery();
         DonationTable.setModel(DbUtils.resultSetToTableModel(rs1));
     }
    
    // when the back button is clicked
    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        AdminDashboard.main(new String[]{});
        dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    // when the donate button is clicked
    private void donatebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_donatebuttonActionPerformed
        try {
            int input;
            input = JOptionPane.showConfirmDialog(Donation.this,"Donation is a one-time process. Are you sure you want to continue ?","Are you sure?",JOptionPane.YES_NO_OPTION);
            if( input == 0)
            {
                int flag = nst.organise();
                nst.distributeItems();
                int new_balance = nst.money_distributions();
                fetch();
                fetch1();
            }
        } catch (SQLException ex) {
            Logger.getLogger(Donation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_donatebuttonActionPerformed

    // when the check expenditure button is clicked
    private void checkexpbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkexpbuttonActionPerformed
        // TODO add your handling code here:
        int expenditure = nst.expenditure();
        String s = "Your expenditure for this year is Rs " + expenditure;
        JOptionPane.showMessageDialog(null, s, "Expenditure", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_checkexpbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Donation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Donation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Donation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Donation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Donation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DonationTable;
    private javax.swing.JTable SortedTable;
    private javax.swing.JButton backbutton;
    private javax.swing.JButton checkexpbutton;
    private javax.swing.JButton donatebutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
