/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import DAO.Donor;
import javax.swing.JOptionPane;

/**
 *
 * @author ayush
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    Donor nd = new Donor();
    public ForgotPassword() {
        initComponents();
    }
    String password = "1234";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        passwordbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FORGOT PASSWORD");
        setResizable(false);
        getContentPane().setLayout(null);

        jTextField1.setBackground(new java.awt.Color(0, 255, 255));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(330, 134, 222, 39);

        jTextField2.setBackground(new java.awt.Color(0, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(330, 203, 222, 42);

        jTextField3.setBackground(new java.awt.Color(0, 255, 255));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(330, 277, 222, 42);

        jLabel1.setText("USER NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(192, 144, 102, 18);

        jLabel2.setText("EMAIL ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(192, 215, 59, 18);

        jLabel3.setText("PHONE NO.");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(192, 289, 82, 18);

        passwordbutton.setText("GET PASSWORD");
        passwordbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(passwordbutton);
        passwordbutton.setBounds(350, 390, 152, 40);

        backbutton.setBackground(new java.awt.Color(102, 255, 102));
        backbutton.setText("BACK");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton);
        backbutton.setBounds(610, 480, 72, 24);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/forgot_password.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-130, 0, 900, 660);

        setSize(new java.awt.Dimension(741, 611));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // when username is entered
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        nd.setUsername(jTextField1.getText());
    }//GEN-LAST:event_jTextField1ActionPerformed

    // when email is entered
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        nd.setEmail(jTextField2.getText());
    }//GEN-LAST:event_jTextField2ActionPerformed

    // when contact is entered
    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
        nd.setContact(jTextField3.getText());
    }//GEN-LAST:event_jTextField3ActionPerformed

    // when password button is clicked
    private void passwordbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordbuttonActionPerformed
        // TODO add your handling code here:
        if("".equals(jTextField1.getText()))
            JOptionPane.showMessageDialog(null,"Username cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if("".equals(jTextField2.getText()))
            JOptionPane.showMessageDialog(null,"Email cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(!jTextField2.getText().trim().contains("@"))
            JOptionPane.showMessageDialog(null,"Invalid Email" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(!jTextField3.getText().trim().matches("[0-9]+"))
            JOptionPane.showMessageDialog(null,"Invalid Phone" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else{
            String newPassword;
            newPassword = nd.validate();
            if("".equals(newPassword))
                JOptionPane.showMessageDialog(null, "No such user found", "ERROR", JOptionPane.ERROR_MESSAGE);
            else
                JOptionPane.showMessageDialog(null,"Your Password : " + newPassword, "Password Retrieved", JOptionPane.INFORMATION_MESSAGE);
            
        }
    }//GEN-LAST:event_passwordbuttonActionPerformed

    // when back button is clicked
    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
        // TODO add your handling code here:
        UserLogin.main(new String[]{});
        dispose();
    }//GEN-LAST:event_backbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton passwordbutton;
    // End of variables declaration//GEN-END:variables
}
