/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import DAO.Donor;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.*;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author ayush
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     */
    Donor user;
    public Signup() {
        this.user = new Donor();
        initComponents();
    }
    
    boolean checked = false;        // checks if the check box is selected or not


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namefield = new javax.swing.JTextField();
        usernamefield = new javax.swing.JTextField();
        emailfield = new javax.swing.JTextField();
        contactfield = new javax.swing.JTextField();
        residencefield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        termscheckbox = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        passwordfield = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DONOR SIGNUP");
        setResizable(false);
        getContentPane().setLayout(null);

        namefield.setText("Enter name");
        namefield.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        namefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namefieldfocuslistener(evt);
            }
        });
        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });
        getContentPane().add(namefield);
        namefield.setBounds(460, 70, 300, 40);

        usernamefield.setText("");
        usernamefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                usernamefocus(evt);
            }
        });
        usernamefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamefieldActionPerformed(evt);
            }
        });
        getContentPane().add(usernamefield);
        usernamefield.setBounds(460, 140, 300, 40);

        emailfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailfieldFocusGained(evt);
            }
        });
        emailfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailfieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailfield);
        emailfield.setBounds(460, 280, 300, 40);

        contactfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                contactfieldFocusGained(evt);
            }
        });
        contactfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactfieldActionPerformed(evt);
            }
        });
        getContentPane().add(contactfield);
        contactfield.setBounds(460, 350, 300, 40);

        residencefield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                residencefieldFocusGained(evt);
            }
        });
        residencefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                residencefieldActionPerformed(evt);
            }
        });
        getContentPane().add(residencefield);
        residencefield.setBounds(460, 410, 300, 41);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(370, 80, 60, 20);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USER NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(320, 140, 140, 22);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 210, 130, 22);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EMAIL ID");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(350, 280, 100, 22);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PHONE NO.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 360, 120, 16);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RESIDENCE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(340, 410, 120, 22);

        termscheckbox.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        termscheckbox.setForeground(new java.awt.Color(255, 255, 255));
        termscheckbox.setText("Agree to terms and conditions");
        termscheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termscheckboxActionPerformed(evt);
            }
        });
        getContentPane().add(termscheckbox);
        termscheckbox.setBounds(460, 490, 340, 26);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(670, 559, 90, 50);

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton2.setText("SIGNUP");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 560, 146, 53);

        passwordfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordfieldFocusGained(evt);
            }
        });
        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });
        getContentPane().add(passwordfield);
        passwordfield.setBounds(460, 210, 300, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Image10.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 800, 660);

        setSize(new java.awt.Dimension(810, 663));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    // when save button is clicked, this function gets called
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        char arr[] = {};
        char arr1[] = {'E', 'n', 't', 'e', 'r', ' ', 'P', 'a', 's', 's', 'w', 'o', 'r', 'd'};
        if(checked == false){
            JOptionPane.showMessageDialog(Signup.this,"Please Accept terms and conditions","Error",JOptionPane.ERROR_MESSAGE);
        }
        else if("Enter Name".equals(namefield.getText()) || "".equals(namefield.getText())  )
            JOptionPane.showMessageDialog(null,"Name cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if("Enter Username".equals(usernamefield.getText())||"".equals(usernamefield.getText()))
            JOptionPane.showMessageDialog(null,"Username cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(Arrays.equals(arr1, passwordfield.getPassword())|| Arrays.equals(arr, passwordfield.getPassword()))
            JOptionPane.showMessageDialog(null,"Password Invalid" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(!emailfield.getText().trim().contains("@"))
            JOptionPane.showMessageDialog(null,"Invalid Email" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(!contactfield.getText().trim().matches("[0-9]+") || contactfield.getText().trim().length() < 7)
            JOptionPane.showMessageDialog(null,"Invalid Phone" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if("Enter Residence".equals(residencefield.getText()) || "".equals(residencefield.getText())  )
            JOptionPane.showMessageDialog(null,"Residence cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(user.validateUsername(usernamefield.getText()))
            JOptionPane.showMessageDialog(null,"Username already exists" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(user.validateEmail(emailfield.getText()))
            JOptionPane.showMessageDialog(null,"Email already exists" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else{
            int input;
            input = JOptionPane.showConfirmDialog(Signup.this,"Do you really want to add this user ?","Are you sure?",JOptionPane.YES_NO_OPTION);
            if( input == 0)
            {       
                    int i = user.save();
                    if(i>0){
                            JOptionPane.showMessageDialog(null, "Account Created Successfully", "Success!", JOptionPane.INFORMATION_MESSAGE);
                            UserLogin.main(new String[]{});
                            dispose();	
                    }
                    else{
                            JOptionPane.showMessageDialog(Signup.this,"Sorry, unable to save!");
                    }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    // when checkbox is ticked, this method gets called
    private void termscheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termscheckboxActionPerformed
        checked = true;
    }//GEN-LAST:event_termscheckboxActionPerformed

    // when namefield is entered
    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
        String name = namefield.getText(); 
        user.setName(name);
    }//GEN-LAST:event_namefieldActionPerformed

    // when usernamefield is entered
    private void usernamefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamefieldActionPerformed
        // TODO add your handling code here:
        user.setUsername(usernamefield.getText());
    }//GEN-LAST:event_usernamefieldActionPerformed
    
    // when passwordfield is entered
    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        // TODO add your handling code here:
         user.setPassword(String.valueOf(passwordfield.getPassword()));
    }//GEN-LAST:event_passwordfieldActionPerformed

    // when email field is entered
    private void emailfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailfieldActionPerformed
        // TODO add your handling code here:
         user.setEmail(emailfield.getText());
    }//GEN-LAST:event_emailfieldActionPerformed
    
    // when contact field is entered
    private void contactfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactfieldActionPerformed
        // TODO add your handling code here:
        user.setContact(contactfield.getText());
    }//GEN-LAST:event_contactfieldActionPerformed
    
    // when residence field is entered
    private void residencefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_residencefieldActionPerformed
        // TODO add your handling code here:
        user.setResidence(residencefield.getText());
    }//GEN-LAST:event_residencefieldActionPerformed
    
    // when back is clicked
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        UserLogin.main(new String[]{});
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passwordfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordfieldFocusGained
        // TODO add your handling code here:
        String temp = new String(passwordfield.getPassword());
        if(temp.equals("Enter Password"))
              passwordfield.setText("");
    }//GEN-LAST:event_passwordfieldFocusGained

    private void emailfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailfieldFocusGained
        // TODO add your handling code here:
        if(emailfield.getText().equals("Enter Email"))
              emailfield.setText("");
    }//GEN-LAST:event_emailfieldFocusGained

    private void contactfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_contactfieldFocusGained
        // TODO add your handling code here:
        if("Enter Phone".equals(contactfield.getText()))
            contactfield.setText("");
    }//GEN-LAST:event_contactfieldFocusGained

    private void residencefieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_residencefieldFocusGained
        // TODO add your handling code here:
        if(residencefield.getText().equals("Enter Residence"))
            residencefield.setText("");
    }//GEN-LAST:event_residencefieldFocusGained
    
    private void namefieldfocuslistener(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namefieldfocuslistener
        // TODO add your handling code here:
        if (namefield.getText().equals("Enter name")) {
            namefield.setText("");
        }
    }//GEN-LAST:event_namefieldfocuslistener
    
    private void usernamefocus(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernamefocus
        // TODO add your handling code here:
        //if (usernamefield.getText().equals("")) {
        //   usernamefield.setText("");
        //}
    }//GEN-LAST:event_usernamefocus
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField contactfield;
    private javax.swing.JTextField emailfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField namefield;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JTextField residencefield;
    private javax.swing.JCheckBox termscheckbox;
    private javax.swing.JTextField usernamefield;
    // End of variables declaration//GEN-END:variables
}
