/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;
import DAO.Donor;
import java.util.Arrays;
import Home.UserDashboard;
import javax.swing.JOptionPane;
/**
 *
 * @author ayush
 */
public class UserLogin extends javax.swing.JFrame {

    /**
     * Creates new form UserLogin
     */
    Donor user;
    String username = "", password;
    public UserLogin() {
        this.password = "";
        this.user = new Donor();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("USER LOGIN");
        setResizable(false);
        getContentPane().setLayout(null);

        jTextField1.setBackground(new java.awt.Color(204, 255, 255));
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(270, 90, 349, 58);

        jPasswordField1.setBackground(new java.awt.Color(204, 255, 255));
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(270, 210, 349, 58);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel1.setText("USER NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 100, 113, 34);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 230, 110, 33);

        jToggleButton1.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButton1.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jToggleButton1.setText("LOGIN");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(369, 325, 164, 53);

        jToggleButton2.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButton2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jToggleButton2.setText("SIGNUP");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(400, 420, 100, 41);

        jToggleButton3.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButton3.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jToggleButton3.setText("FORGOT PASSWORD");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3);
        jToggleButton3.setBounds(360, 490, 190, 40);

        jToggleButton4.setBackground(new java.awt.Color(204, 255, 255));
        jToggleButton4.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jToggleButton4.setText("BACK");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton4);
        jToggleButton4.setBounds(677, 526, 80, 21);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Image33.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 840, 630);

        setSize(new java.awt.Dimension(850, 630));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // setting the username 
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        this.username = jTextField1.getText();
    }//GEN-LAST:event_jTextField1ActionPerformed

    // signup button clicked
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        Signup.main(new String[]{});
        dispose();
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    // forgot password clicked
    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        //ForgotPassword.main(new String[]{});
        ForgotPassword.main(new String []{});
        dispose();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    // login button clicked and following validation is performed
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        char arr[] = {};
        char arr1[] = {'E', 'n', 't', 'e', 'r', ' ', 'P', 'a', 's', 's', 'w', 'o', 'r', 'd'};
        if("Enter Username".equals(jTextField1.getText()) || "".equals(jTextField1.getText()))
            JOptionPane.showMessageDialog(null,"Username cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else if(Arrays.equals(arr, jPasswordField1.getPassword())|| Arrays.equals(arr1, jPasswordField1.getPassword()))
            JOptionPane.showMessageDialog(null,"Password cannot be empty" , "ERROR", JOptionPane.ERROR_MESSAGE);
        else{
            int i;
            i = user.get_id(this.username, this.password);
            if(i>0){
                UserDashboard u1 = new UserDashboard();
                u1.setid(i);
                u1.setVisible(true);
                //JOptionPane.showMessageDialog(this, "Viola! You did it!!!!");
                dispose();

            }
            else{
                JOptionPane.showMessageDialog(null,"Wrong username or password", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        this.password = new String(jPasswordField1.getPassword());
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        if("Enter Username".equals(jTextField1.getText()))
            jTextField1.setText("");
    }//GEN-LAST:event_jTextField1FocusGained

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
        if("Enter Password".equals(new String(jPasswordField1.getPassword())))
            jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        Homepage.main(new String[]{});
        dispose();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    // End of variables declaration//GEN-END:variables
}
